### ISSUE TITLE
The `master` branch fails to compile

### ISSUE THREAD

**Issue by fvigotti** [spring-cloud-stream-app-starters/time#4]
I've created a pull request because this package doesn't even compile..
https://github.com/spring-cloud-stream-app-starters/time/pull/3

NOW , the question is... how do you have built 
repo.spring.io -> spring-cloud-starter-stream-source-time-2.0.0.BUILD-20180220.153824-11.pom
?
do you have another source repository ? how can you compile and push to repository code that doesn't compile ? I'm asking this because I want to know if the code that I download from repo.spring.io is built from this source ...

Thank you,
Francesco

**Comment by sabbyanandan** [comment]
Hi, @fvigotti. Sorry, you're having trouble. Please stick to the [1.3.x branch](https://github.com/spring-cloud-stream-app-starters/time/tree/1.3.x). That is the GA release branch and `master` is in development/refactoring mode at the moment.

**Comment by artembilan** [comment]
I consider this as fixed via https://github.com/spring-cloud-stream-app-starters/time/commit/26579254d7cf545b408f9af725d8b1be108bb700 and https://github.com/spring-cloud-stream-app-starters/time/commit/c43f18760f85514d4fc0c59bd2ca7fcf993d9f21
