### ISSUE TITLE
Compilation error while using mvn install 

### ISSUE THREAD

**Issue by ambarnigade** [spring-cloud-stream-app-starters/time#5]
getting below error while compiling

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project spring-cloud-starter-stream-source-time: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
have following environment

openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.17.10.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

**Comment by artembilan** [comment]
I have just done this from the current `master` and got results like:
```
~\spring-cloud-stream-app-starters\time>mvnw clean install
...
[INFO] Installing ~\spring-cloud-stream-app-starters\time\time-app-dependencies\pom.xml to ~\.m2\repository\org\springframework\cloud\stream\app\time-app-dependencies\2.0.1.BUILD-SNAPSHOT\time-app-dependencies-2.0.1.BUILD-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] time-app-starters-build ............................ SUCCESS [  4.976 s]
[INFO] spring-cloud-starter-stream-source-time ............ SUCCESS [ 22.616 s]
[INFO] time-app-dependencies .............................. SUCCESS [  0.066 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.434 s
[INFO] Finished at: 2018-07-16T11:14:14-04:00
[INFO] Final Memory: 53M/273M
[INFO] ------------------------------------------------------------------------
```

So, everything works well. It's indeed might be a problem of your environment and you might just not have a proper `JAVA_HOME` ENV var: https://www.google.com/search?q=set+JAVA_HOME

Also pay attention how I use a Maven Wrapper (`mvnw` command), embedded into the project instead of installed locally. In fact I stopped to use a local Maven for a while...
